import Head from "next/head";
import Navigation from '../components/Navigation'
import ProjectListings from "../components/ProjectListings";

export default function Design() {
  return (
    <div className="font-sans relative overflow-hidden">
      <Head>
        <title>Zhiyuan Zhang - Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Navigation />

      <main>
        <ProjectListings />
      </main>
      <footer className="text-center p-8">
        &copy; Designed and developed by Zhiyuan Zhang
        {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      </footer>

    </div>
  )
}